apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: guestbook-ui
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: guestbook-ui
